---
language: node_js
node_js:
  - "4"

sudo: false

notifications:
  email:
    - stefan.kedl@unicasum.net
    - markus.felten@gmx.de

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@latest"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
